[package]
name = "ijssel"
version = "0.1.0"
authors = ["Nick Vernij <hello@nickforall.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "100"
libc = "0.2"